### ISSUE TITLE
demo中keyboard点击任何按键输入内容会报错，提示缺少VIBRATE权限

### ISSUE THREAD

**Issue by AweiLoveAndroid** [goweii/Layer#15]
demo的Keyboard，点击输入内容就崩溃了，错误如下：

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: per.goweii.layer, PID: 21182
    java.lang.SecurityException: Requires VIBRATE permission
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
        at android.os.Parcel.createException(Parcel.java:2360)
        at android.os.Parcel.readException(Parcel.java:2343)
        at android.os.Parcel.readException(Parcel.java:2285)
        at android.os.IVibratorService$Stub$Proxy.vibrate(IVibratorService.java:543)
        at android.os.SystemVibrator.vibrate(SystemVibrator.java:245)
        at android.os.Vibrator.vibrate(Vibrator.java:397)
        at android.os.Vibrator.vibrate(Vibrator.java:380)
        at per.goweii.layer.keyboard.KeyboardVibratorEffect.performClick(KeyboardVibratorEffect.java:23)
        at per.goweii.layer.keyboard.KeyboardLayer.performVibratorEffect(KeyboardLayer.java:272)
        at per.goweii.layer.keyboard.KeyboardLayer.performFeedback(KeyboardLayer.java:261)
        at per.goweii.layer.keyboard.KeyboardGesture$KeyboardGestureListener.onSingleTapUp(KeyboardGesture.java:87)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:758)
        at per.goweii.layer.keyboard.KeyboardGesture$1.onTouch(KeyboardGesture.java:33)
        at android.view.View.dispatchTouchEvent(View.java:14374)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at per.goweii.layer.core.widget.MaxSizeFrameLayout.dispatchTouchEvent(MaxSizeFrameLayout.java:52)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at per.goweii.layer.core.widget.SwipeLayout.dispatchTouchEvent(SwipeLayout.java:110)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3152)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:571)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1880)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4305)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:529)
        at android.view.View.dispatchPointerEvent(View.java:14654)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6365)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6129)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5568)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5625)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5591)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5743)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5599)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5800)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5572)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5625)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5591)
E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5599)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5572)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8496)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8447)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8407)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8633)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:241)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:8163)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.VibratorService.vibrate(VibratorService.java:804)
        at android.os.IVibratorService$Stub.onTransact(IVibratorService.java:279)
        at android.os.Binder.execTransactInternal(Binder.java:1160)
        at android.os.Binder.execTransact(Binder.java:1129)

```

**Comment by goweii** [comment]
加上权限呗，这只是个普通权限。
