### ISSUE TITLE
如何让Layer覆盖SystemUI?

### ISSUE THREAD

**Issue by zuilintan** [goweii/Layer#16]
看了下API和源码, 
发现并没有暴露相关内容, 
有支持的计划, 或者临时的对策嘛?

**Comment by goweii** [comment]
systemui指啥？状态栏和导航栏图标？这个覆盖不了。

**Comment by zuilintan** [comment]
对的, 状态栏和导航栏, 

那有无办法可以用一个新的Window承载Layer吗, 
如此, 就可以通过为新的window设置type覆盖SystemUI

**Comment by goweii** [comment]
你试下继承Layer，重写onGetParent方法，返回一个你自定义window的view

**Comment by zuilintan** [comment]
我用windowManager addView的方式, 添加了一个viewGourp, 
```
@NonNull
@Override
protected ViewGroup onGetParent() {
    WindowManager windowManager = (WindowManager) getSystemService(Context.WINDOW_SERVICE);
    WindowManager.LayoutParams params = new WindowManager.LayoutParams(
            WindowManager.LayoutParams.MATCH_PARENT,
            WindowManager.LayoutParams.MATCH_PARENT,
            2066,
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
            PixelFormat.RGB_888);
    LevelLayout frameLayout = new LevelLayout(MainActivity.this, 3000);
    frameLayout.setBackgroundColor(Color.BLACK);
    windowManager.addView(frameLayout, params);
    return frameLayout;
}
```

然后在onShowListener里, 写了如下代码: 

```
FragmentStatePagerAdapter fragmentStatePagerAdapter = new FragmentStatePagerAdapter(MainActivity.this.getSupportFragmentManager(), FragmentStatePagerAdapter.BEHAVIOR_RESUME_ONLY_CURRENT_FRAGMENT) {
                @Override
                public int getCount() {
                    return quickStartItemNode.getNodeChildren().size();
                }

                @NonNull
                @Override
                public Fragment getItem(int position) {
                    return QuickStartL3Fragment.newInstance(quickStartItemNode.getNodeChildren().get(position), null);
                }
            };
            ViewPager viewPager = (ViewPager) layer.getView(R.id.vp2_dialog_content);
            viewPager.setAdapter(fragmentStatePagerAdapter);
```

报错如下: 

```
    java.lang.IllegalArgumentException: No view found for id 0x7f0802f1 (com.adayo.app.userguide:id/vp2_dialog_content) for fragment QuickStartL3Fragment{ccee225} (ee16abeb-dfde-4ee9-ab6b-ca47ceef1c3e id=0x7f0802f1)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540)
        at com.adayo.app.userguide.ui.page.activity.MainActivity$MyLayerListenerImpl.onShown(MainActivity.java:268)
```

这个报错有些无法理解, 它尝试在QuickStartL3Fragment中去找vp2_dialog_content, 但二者明明没有直接关系才对

**Comment by goweii** [comment]
报错里面有viewpager的堆栈，说明viewpager已经找到了。报错里面的id是不是你fragment里面的？

**Comment by zuilintan** [comment]
> 报错里面有viewpager的堆栈，说明viewpager已经找到了。报错里面的id是不是你fragment里面的？

不是， 是AnyLayer布局里的，
这就是最奇怪的点， 它尝试在Fragment的布局中，去找AnyLayer的布局中的id

**Comment by goweii** [comment]
你调试下吧，我看不出来

**Comment by zuilintan** [comment]
嗯，麻烦了
