### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by JianyangGit** [goweii/Layer#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.core.graphics.Insets androidx.core.view.WindowInsetsCompat.getInsets(int)' on a null object reference
        at per.goweii.layer.core.DecorLayer.getDecorInsets(DecorLayer.java:138)
        at per.goweii.layer.core.DecorLayer$WindowInsetsChangedListener.onControllableInsetsChanged(DecorLayer.java:192)
        at androidx.core.view.WindowInsetsControllerCompat$Impl30$2.onControllableInsetsChanged(WindowInsetsControllerCompat.java:744)
        at android.view.InsetsController.invokeControllableInsetsChangedListeners(InsetsController.java:1592)
        at android.view.InsetsController.onControlsChanged(InsetsController.java:852)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8488)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:8436)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:503)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:444)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:163)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5547)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2259)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8085)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

复现流程：使用权限申请，跳转到了设置页面，然后返回，闪退

**Comment by goweii** [comment]
试下1.0.1
